// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcgRf1ycx1Ze101Y7mrrBgtj_8ZuM_NCU',
    appId: '1:674471536194:android:d47f6062f42d44323eafdb',
    messagingSenderId: '674471536194',
    projectId: 'alamal-pharmacy-dedb1',
    storageBucket: 'alamal-pharmacy-dedb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2xDctd3Ydl0EjS2peJwOmezUpc5mYkB4',
    appId: '1:674471536194:ios:8cc2c45ca81af6ee3eafdb',
    messagingSenderId: '674471536194',
    projectId: 'alamal-pharmacy-dedb1',
    storageBucket: 'alamal-pharmacy-dedb1.firebasestorage.app',
    iosClientId: '674471536194-mn5aagot44uom5dbnmm4rng2eie3qmce.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmacyAlamal',
  );
}
